local AIConfig = {}

AIConfig.profiles = {
	passiveWild = {
		brainType = "passiveWild",
		thinkInterval = 0.25,
		dormantThinkInterval = 1.2,
		idleSleepDuration = 2.0,
		activityRadius = 34,
		engagedMemorySeconds = 2.2,
		targetLockSeconds = 0.8,
		leashRadius = 60,
		aggroRadius = 42,
		disengageRadius = 78,
		preferredRange = 14,
		roamRadius = 26,
		movementRefresh = 0.9,
		retainBias = 4,
		ownerThreatBias = 0,
		holdDefenseRange = 0,
		movementByState = {
			follow = 0.75,
			chase = 0.85,
			return = 0.82,
			flee = 0.9,
			roam = 0.58,
			hold = 0,
			idle = 0,
		},
		tactical = { offensive = 0.25, defensive = 0.45, utility = 0.55, mobility = 0.2, status = 0.1 },
	},
	hostileWild = {
		brainType = "hostileWild",
		thinkInterval = 0.2,
		dormantThinkInterval = 1.0,
		idleSleepDuration = 1.6,
		activityRadius = 42,
		engagedMemorySeconds = 2.8,
		targetLockSeconds = 1.5,
		leashRadius = 86,
		aggroRadius = 66,
		disengageRadius = 112,
		preferredRange = 12,
		roamRadius = 34,
		movementRefresh = 0.7,
		retainBias = 14,
		ownerThreatBias = 0,
		holdDefenseRange = 0,
		movementByState = {
			follow = 0.82,
			chase = 0.92,
			return = 0.88,
			flee = 0.95,
			roam = 0.62,
			hold = 0,
			idle = 0,
		},
		tactical = { offensive = 0.25, defensive = 0.45, utility = 0.55, mobility = 0.2, status = 0.1 },
	},
	petFollower = {
		brainType = "petFollower",
		thinkInterval = 0.18,
		dormantThinkInterval = 0.18,
		idleSleepDuration = 0,
		activityRadius = 0,
		engagedMemorySeconds = 3.2,
		targetLockSeconds = 1.2,
		leashRadius = 90,
		aggroRadius = 68,
		disengageRadius = 110,
		preferredRange = 11,
		roamRadius = 24,
		movementRefresh = 0.55,
		retainBias = 18,
		ownerThreatBias = 28,
		holdDefenseRange = 30,
		movementByState = {
			follow = 0.82,
			chase = 0.95,
			return = 0.9,
			flee = 1.0,
			roam = 0.68,
			hold = 0,
			idle = 0,
		},
		tactical = { offensive = 0.5, defensive = 0.45, utility = 0.35, mobility = 0.35, status = 0.3 },
	},
}

return AIConfig
