local Players = game:GetService("Players")
local PlayerScripts = script.Parent
local Controllers = PlayerScripts:WaitForChild("Controllers")

local PartyController = require(Controllers:WaitForChild("PartyController"))
local CommandController = require(Controllers:WaitForChild("CommandController"))
local BuildController = require(Controllers:WaitForChild("BuildController"))
local ItemController = require(Controllers:WaitForChild("ItemController"))
local UIController = require(Controllers:WaitForChild("UIController"))
local StarterController = require(Controllers:WaitForChild("StarterController"))
local InputController = require(Controllers:WaitForChild("InputController"))

local localPlayer = Players.LocalPlayer
local party = PartyController.new()
local build = BuildController.new()
local items = ItemController.new(party)
local command = CommandController.new(party)
local ui = UIController.new(build, items, party, command)
local starter = StarterController.new()
local input = InputController.new(party, command, build, ui)

local mouse = localPlayer:GetMouse()
build:bind(mouse)
items:bind()
command:bind(mouse)
ui:bind()
starter:bind()
input:bind()
command:setActiveSlot(party.selectedSlot)
command:setControlMode(party.controlMode)
